# Generated by Django 4.2.4 on 2024-01-11 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='contact_number',
            new_name='customer_id',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='Company_name',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='Warehose_location',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='seller_id',
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(max_length=255)),
                ('Company_name', models.CharField(max_length=200)),
                ('Warehose_location', models.CharField(max_length=200)),
                ('contact_number', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
