# Generated by Django 4.2.4 on 2024-01-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='customer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
