# Generated by Django 4.2.4 on 2024-01-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_customerprofile_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='Company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='Warehose_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='contact_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='seller_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
