# Generated by Django 4.2.4 on 2024-01-14 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_sellerprofile_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='seller_id',
        ),
    ]
