# Generated by Django 4.2.4 on 2024-01-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_sellerprofile_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Accessesires', 'Accessesiries'), ('Arts', 'Arts'), ('Electronics', 'Electronics'), ('Shirts', 'Shirts'), ('Shoes', 'Shoes'), ('Homedecors', 'Homedecors'), ('Gifts', 'Gifts')], default='Homedecors', max_length=20),
        ),
    ]
